version: '3.8'

services:
  db_core:
    image: postgres:15
    volumes:
      - ./postgres_core_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  db_fetcher:
    image: postgres:15
    volumes:
      - ./postgres_fetcher_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis:7-alpine
    volumes:
      - ./redis_data:/data
    ports:
      - "6380:6379"
  app_core:
    build: ./app_core
    volumes:
      - ./app_core:/app
    ports:
      - "3000:3000"
    depends_on:
      - db_core
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      REDIS_URL_STREAM: redis://redis:6379/2

  app_fetcher:
    build: ./app_fetcher
    volumes:
      - ./app_fetcher:/app
    ports:
      - "3001:3001"
    depends_on:
      - db_fetcher
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
      REDIS_URL_STREAM: redis://redis:6379/2

  fetcher_worker:
    build: ./app_fetcher
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - ./app_fetcher:/app
    depends_on:
      - db_fetcher
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      REDIS_URL_SIDEKIQ: redis://redis:6379/1
      REDIS_URL_STREAM: redis://redis:6379/2
