# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `prop` gem.
# Please instead update this file by running `bin/tapioca gem prop`.


# pkg:gem/prop#lib/prop/rate_limited.rb:2
module Prop
  class << self
    # pkg:gem/prop#lib/prop.rb:12
    def after_evaluated(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:11
    def before_throttle(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:11
    def cache(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:11
    def cache=(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:11
    def configurations(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:11
    def configure(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:12
    def count(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:11
    def disabled(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:12
    def query(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:11
    def read(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:12
    def reset(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:12
    def throttle(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:12
    def throttle!(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:12
    def throttled?(*args, **_arg1, &block); end

    # pkg:gem/prop#lib/prop.rb:11
    def write(*args, **_arg1, &block); end
  end
end

# pkg:gem/prop#lib/prop/interval_strategy.rb:6
class Prop::IntervalStrategy
  class << self
    # Builds the expiring cache key
    #
    # pkg:gem/prop#lib/prop/interval_strategy.rb:41
    def build(options); end

    # @return [Boolean]
    #
    # pkg:gem/prop#lib/prop/interval_strategy.rb:31
    def compare_threshold?(counter, operator, options); end

    # pkg:gem/prop#lib/prop/interval_strategy.rb:12
    def counter(cache_key, options); end

    # @raise [ArgumentError]
    #
    # pkg:gem/prop#lib/prop/interval_strategy.rb:22
    def decrement(cache_key, amount, options = T.unsafe(nil)); end

    # @return [Boolean]
    #
    # pkg:gem/prop#lib/prop/interval_strategy.rb:36
    def first_throttled?(counter, options); end

    # options argument is kept for api consistency for all strategies
    #
    # @raise [ArgumentError]
    #
    # pkg:gem/prop#lib/prop/interval_strategy.rb:17
    def increment(cache_key, amount, options = T.unsafe(nil)); end

    # pkg:gem/prop#lib/prop/interval_strategy.rb:27
    def reset(cache_key, options = T.unsafe(nil)); end

    # pkg:gem/prop#lib/prop/interval_strategy.rb:52
    def threshold_reached(options); end

    # pkg:gem/prop#lib/prop/interval_strategy.rb:58
    def validate_options!(options); end

    # pkg:gem/prop#lib/prop/interval_strategy.rb:8
    def zero_counter; end

    private

    # pkg:gem/prop#lib/prop/interval_strategy.rb:78
    def cache; end

    # @raise [ArgumentError]
    #
    # pkg:gem/prop#lib/prop/interval_strategy.rb:74
    def validate_interval(option, key); end

    # @raise [ArgumentError]
    #
    # pkg:gem/prop#lib/prop/interval_strategy.rb:70
    def validate_threshold(option, key); end
  end
end

# pkg:gem/prop#lib/prop/key.rb:5
class Prop::Key
  class << self
    # Simple key expansion only supports arrays and primitives
    #
    # pkg:gem/prop#lib/prop/key.rb:8
    def normalize(key); end
  end
end

# pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:6
class Prop::LeakyBucketStrategy
  class << self
    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:8
    def _throttle_leaky_bucket(handle, key, cache_key, options); end

    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:73
    def build(options); end

    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:105
    def cache; end

    # @return [Boolean]
    #
    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:69
    def compare_threshold?(bucket, operator, options); end

    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:16
    def counter(cache_key, options); end

    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:54
    def decrement(cache_key, amount, options); end

    # WARNING: race condition
    # this increment is not atomic, so it might miss counts when used frequently
    #
    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:34
    def increment(cache_key, amount, options); end

    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:20
    def leak_amount(bucket, amount, options, now); end

    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:65
    def reset(cache_key, options = T.unsafe(nil)); end

    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:82
    def threshold_reached(options); end

    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:26
    def update_bucket(current_bucket_size, max_bucket_size, amount); end

    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:89
    def validate_options!(options); end

    # pkg:gem/prop#lib/prop/leaky_bucket_strategy.rb:101
    def zero_counter; end
  end
end

# pkg:gem/prop#lib/prop/limiter.rb:9
class Prop::Limiter
  class << self
    # pkg:gem/prop#lib/prop/limiter.rb:42
    def after_evaluated(&blk); end

    # Returns the value of attribute after_evaluated_callback.
    #
    # pkg:gem/prop#lib/prop/limiter.rb:12
    def after_evaluated_callback; end

    # Sets the attribute after_evaluated_callback
    #
    # @param value the value to set the attribute after_evaluated_callback to.
    #
    # pkg:gem/prop#lib/prop/limiter.rb:12
    def after_evaluated_callback=(_arg0); end

    # pkg:gem/prop#lib/prop/limiter.rb:38
    def before_throttle(&blk); end

    # Returns the value of attribute before_throttle_callback.
    #
    # pkg:gem/prop#lib/prop/limiter.rb:12
    def before_throttle_callback; end

    # Sets the attribute before_throttle_callback
    #
    # @param value the value to set the attribute before_throttle_callback to.
    #
    # pkg:gem/prop#lib/prop/limiter.rb:12
    def before_throttle_callback=(_arg0); end

    # Returns the value of attribute cache.
    #
    # pkg:gem/prop#lib/prop/limiter.rb:12
    def cache; end

    # Sets the attribute cache
    #
    # @param value the value to set the attribute cache to.
    #
    # pkg:gem/prop#lib/prop/limiter.rb:12
    def cache=(cache); end

    # Returns the value of attribute handles.
    #
    # pkg:gem/prop#lib/prop/limiter.rb:145
    def configurations; end

    # Public: Registers a handle for rate limiting
    #
    # handle   - the name of the handle you wish to use in your code, e.g. :login_attempt
    # defaults - the settings for this handle, e.g. { threshold: 5, interval: 5.minutes }
    #
    # Raises Prop::RateLimited if the number if the threshold for this handle has been reached
    #
    # pkg:gem/prop#lib/prop/limiter.rb:52
    def configure(handle, defaults); end

    # Public: Counts the number of times the given handle/key combination has been hit in the current window
    #
    # handle   - the throttle identifier
    # key      - the associated key
    #
    # Returns a count of hits in the current window
    #
    # pkg:gem/prop#lib/prop/limiter.rb:136
    def count(handle, key = T.unsafe(nil), options = T.unsafe(nil)); end

    # Public: Disables Prop for a block of code
    #
    # block    - a block of code within which Prop will not raise
    #
    # pkg:gem/prop#lib/prop/limiter.rb:62
    def disabled(&_block); end

    # Returns the value of attribute handles.
    #
    # pkg:gem/prop#lib/prop/limiter.rb:12
    def handles; end

    # Sets the attribute handles
    #
    # @param value the value to set the attribute handles to.
    #
    # pkg:gem/prop#lib/prop/limiter.rb:12
    def handles=(_arg0); end

    # Public: Counts the number of times the given handle/key combination has been hit in the current window
    #
    # handle   - the throttle identifier
    # key      - the associated key
    #
    # Returns a count of hits in the current window
    #
    # pkg:gem/prop#lib/prop/limiter.rb:140
    def query(handle, key = T.unsafe(nil), options = T.unsafe(nil)); end

    # pkg:gem/prop#lib/prop/limiter.rb:14
    def read(&blk); end

    # Public: Resets a specific throttle
    #
    # handle   - the throttle identifier
    # key      - the associated key
    #
    # Returns nothing
    #
    # pkg:gem/prop#lib/prop/limiter.rb:125
    def reset(handle, key = T.unsafe(nil), options = T.unsafe(nil)); end

    # Public: Records a single action for the given handle/key combination.
    #
    # handle  - the registered handle associated with the action
    # key     - a custom request specific key, e.g. [ account.id, "download", request.remote_ip ]
    # options - request specific overrides to the defaults configured for this handle
    # (optional) a block of code that this throttle is guarding
    #
    # Returns true if the threshold for this handle has been reached, else returns false
    #
    # pkg:gem/prop#lib/prop/limiter.rb:77
    def throttle(handle, key = T.unsafe(nil), options = T.unsafe(nil)); end

    # Public: Records a single action for the given handle/key combination.
    #
    # handle  - the registered handle associated with the action
    # key     - a custom request specific key, e.g. [ account.id, "download", request.remote_ip ]
    # options - request specific overrides to the defaults configured for this handle
    # (optional) a block of code that this throttle is guarding
    #
    # Raises Prop::RateLimited if the threshold for this handle has been reached
    # Returns the value of the block if given a such, otherwise the current count of the throttle
    #
    # pkg:gem/prop#lib/prop/limiter.rb:92
    def throttle!(handle, key = T.unsafe(nil), options = T.unsafe(nil), &block); end

    # Public: Is the given handle/key combination currently throttled ?
    #
    # handle   - the throttle identifier
    # key      - the associated key
    #
    # Returns true if a call to `throttle!` with same parameters would raise, otherwise false
    #
    # @return [Boolean]
    #
    # pkg:gem/prop#lib/prop/limiter.rb:113
    def throttled?(handle, key = T.unsafe(nil), options = T.unsafe(nil)); end

    # pkg:gem/prop#lib/prop/limiter.rb:18
    def write(&blk); end

    private

    # pkg:gem/prop#lib/prop/limiter.rb:153
    def _throttle(strategy, handle, key, cache_key, options); end

    # @return [Boolean]
    #
    # pkg:gem/prop#lib/prop/limiter.rb:185
    def disabled?; end

    # @return [Boolean]
    #
    # pkg:gem/prop#lib/prop/limiter.rb:149
    def leaky_bucket_strategy?(strategy); end

    # pkg:gem/prop#lib/prop/limiter.rb:189
    def prepare(handle, key, params); end
  end
end

# pkg:gem/prop#lib/prop/options.rb:5
class Prop::Options
  class << self
    # Sanitizes the option set and sets defaults
    #
    # pkg:gem/prop#lib/prop/options.rb:8
    def build(options); end

    # pkg:gem/prop#lib/prop/options.rb:25
    def get_strategy(options); end

    # pkg:gem/prop#lib/prop/options.rb:35
    def leaky_bucket; end

    # pkg:gem/prop#lib/prop/options.rb:21
    def validate_options!(options); end
  end
end

# pkg:gem/prop#lib/prop/rate_limited.rb:3
class Prop::RateLimited < ::StandardError
  # @return [RateLimited] a new instance of RateLimited
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:6
  def initialize(options); end

  # Returns the value of attribute cache_key.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def cache_key; end

  # Sets the attribute cache_key
  #
  # @param value the value to set the attribute cache_key to.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def cache_key=(_arg0); end

  # pkg:gem/prop#lib/prop/rate_limited.rb:20
  def config; end

  # Returns the value of attribute description.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def description; end

  # Sets the attribute description
  #
  # @param value the value to set the attribute description to.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def description=(_arg0); end

  # Returns the value of attribute first_throttled.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def first_throttled; end

  # Sets the attribute first_throttled
  #
  # @param value the value to set the attribute first_throttled to.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def first_throttled=(_arg0); end

  # Returns the value of attribute handle.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def handle; end

  # Sets the attribute handle
  #
  # @param value the value to set the attribute handle to.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def handle=(_arg0); end

  # Returns the value of attribute retry_after.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def retry_after; end

  # Sets the attribute retry_after
  #
  # @param value the value to set the attribute retry_after to.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def retry_after=(_arg0); end

  # Returns the value of attribute threshold.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def threshold; end

  # Sets the attribute threshold
  #
  # @param value the value to set the attribute threshold to.
  #
  # pkg:gem/prop#lib/prop/rate_limited.rb:4
  def threshold=(_arg0); end
end

# pkg:gem/prop#lib/prop.rb:6
Prop::VERSION = T.let(T.unsafe(nil), String)
