schedule_price_updates:
  cron: "0 * * * *"
  class: "PriceScheduler"
  queue: default

schedule_inventory_value_updates:
  cron: "0 0 * * *"
  class: "InventoryValueScheduler"
  queue: default

schedule_user_inventory_sync:
  cron: "0 1 * * *"
  class: "UserInventorySyncScheduler"
  queue: default
